apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-python
  name: hello-world-python
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hello-world-python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
      - image: in28min/hello-world-python:0.0.2.RELEASE #CHANGE
        imagePullPolicy: IfNotPresent
        name: hello-world-python
        # env:
        #   - name: CURRENCY_EXCHANGE_SERVICE_HOST
        #     value: http://currency-exchange
        
        #     valueFrom: 
        #       configMapKeyRef:
        #         key: CURRENCY_EXCHANGE_SERVICE_HOST
        #         name: currency-conversion-config-map
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: hello-world-python
  name: hello-world-python
  namespace: default
spec:
  ports:
  - port: 8200 #CHANGE
    protocol: TCP
    targetPort: 8200 #CHANGE
  selector:
    app: hello-world-python
  sessionAffinity: None #CHANGE
  type: LoadBalancer